"""Консты для Foodgram API."""

DEFAULT_PAGE_SIZE = 6
MAX_NAME_LENGTH = 150
MAX_EMAIL_LENGTH = 254
MAX_TAG_NAME_LENGTH = 32
MAX_SLUG_LENGTH = 32
MAX_INGREDIENT_NAME_LENGTH = 128
MAX_RECIPE_NAME_LENGTH = 256
MAX_SHORT_LINK_LENGTH = 10
MAX_MEASUREMENT_UNIT_LENGTH = 64
MAX_COOKING_TIME = 600
MAX_INGREDIENT_AMOUNT = 5000
MIN_COOKING_TIME = 1
MIN_INGREDIENT_AMOUNT = 1
