version: '3.3'

services:
  db:
    container_name: foodgram-db
    image: postgres:13.10
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    restart: always

  backend:
    container_name: foodgram-backend
    build:
      context: ../backend/
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - foodgram_static:/backend_static
      - foodgram_media:/app/media
      - data_value:/code/data/
    restart: always

  frontend:
    container_name: foodgram-front
    depends_on:
      - backend
    build:
      context: ../frontend/
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
    # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - foodgram_static:/var/html/static/
      - foodgram_media:/var/html/media/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  foodgram_pg_data:
  foodgram_static:
  foodgram_media:
  data_value:
